import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Skeleton, Stack, useTheme } from '@mui/material';
const CourseDetailSkeleton = () => {
    const theme = useTheme();
    return (_jsx(Box, { sx: { bgcolor: theme.palette.background.paper, minHeight: '100vh', color: 'text.primary' }, children: _jsxs(Stack, { direction: "row", spacing: 4, sx: { p: 3 }, children: [_jsxs(Stack, { spacing: 3, sx: { flex: 1 }, children: [_jsxs(Box, { children: [_jsx(Skeleton, { variant: "text", width: "60%", height: 40, sx: { mb: 1 } }), _jsxs(Box, { sx: { display: 'flex', alignItems: 'center', gap: 1, mb: 2 }, children: [_jsx(Skeleton, { variant: "text", width: 100 }), _jsx(Skeleton, { variant: "text", width: 100 })] })] }), _jsxs(Stack, { direction: "row", spacing: 1, alignItems: "center", children: [_jsx(Skeleton, { variant: "circular", width: 40, height: 40 }), _jsx(Skeleton, { variant: "text", width: 150 })] }), _jsx(Skeleton, { variant: "text", width: "90%" }), _jsx(Skeleton, { variant: "text", width: "40%" }), _jsxs(Box, { sx: { mt: 4 }, children: [_jsx(Skeleton, { variant: "text", width: "40%", height: 32, sx: { mb: 2 } }), _jsx(Skeleton, { variant: "text", width: "60%", sx: { mb: 2 } }), [...Array(4)].map((_, index) => (_jsxs(Stack, { sx: {
                                        p: 2,
                                        mb: 1,
                                        border: 1,
                                        borderColor: 'divider',
                                        borderRadius: 1,
                                        bgcolor: theme.palette.background.paper2
                                    }, direction: "row", justifyContent: "space-between", alignItems: "center", children: [_jsx(Skeleton, { variant: "text", width: "70%" }), _jsx(Skeleton, { variant: "text", width: "20%" })] }, index)))] })] }), _jsx(Box, { sx: { width: 400 }, children: _jsxs(Box, { sx: { position: 'sticky', top: 20 }, children: [_jsx(Box, { sx: { position: 'relative', mb: 3 }, children: _jsx(Skeleton, { variant: "rectangular", width: "100%", height: 225, sx: { borderRadius: 2 } }) }), _jsxs(Stack, { spacing: 2, sx: { p: 2, bgcolor: theme.palette.background.paper2, borderRadius: 2 }, children: [_jsxs(Stack, { direction: "row", alignItems: "center", spacing: 1, children: [_jsx(Skeleton, { variant: "text", width: 120, height: 40 }), _jsx(Skeleton, { variant: "text", width: 100, sx: { opacity: 0.5 } })] }), _jsxs(Stack, { direction: "row", spacing: 1, children: [_jsx(Skeleton, { variant: "rectangular", width: "70%", height: 40, sx: { borderRadius: 1 } }), _jsx(Skeleton, { variant: "rectangular", width: "30%", height: 40, sx: { borderRadius: 1 } })] }), _jsx(Skeleton, { variant: "rectangular", width: "100%", height: 48, sx: { borderRadius: 1 } }), _jsx(Skeleton, { variant: "text", width: "50%", height: 32, sx: { mt: 2, mb: 1 } }), _jsx(Stack, { spacing: 2, children: [...Array(3)].map((_, index) => (_jsx(Skeleton, { variant: "text", width: "80%" }, index))) })] })] }) })] }) }));
};
export default CourseDetailSkeleton;
